### ISSUE TITLE
list of samples to add 

### ISSUE THREAD

**Issue by Cerchie** [stepzen-dev/examples#10]
- [x] [with-gatsby](https://github.com/stepzen-dev/netlify-gatsby-app) <- There are gatsby instructions, but no StepZen instructions
- [x] [with-next](https://github.com/stepzen-dev/netlify-next-app) <- There are netlify/next instructions, but no StepZen instructions
- [x] [with-firebase-nextjs-dashboard](https://github.com/stepzen-dev/next-auth-dashboard) <- Needs full re-write -- this is no longer a challenge but a stable sample. 
- [x] [with-google-analytics](https://github.com/stepzen-dev/demo-event-tracking) <- needs readme -- only boilerplate c-r-a readme is present
- [x] [with-react-native](https://github.com/stepzen-dev/react-native-stepzen) <- partway there, needs context/background info, needs instructions on how to install StepZen 
- [ ] [with-nuxt](https://github.com/stepzen-dev/stepzen-nuxt) <- partway there, needs instructions on how to install StepZen 
- [x] [with-shopify-agility-cms](https://github.com/stepzen-samples/vercel-commerce-stepzen)
- [x] [with-google-login](https://github.com/stepzen-samples/faunadb-login-demo)
- [x] [with-supabase](https://github.com/stepzen-samples/stepzen-supabase)
- [ ] [with-redwood](https://github.com/stepzen-samples/stepzen-redwood)
- [ ] [with-apigee](https://github.com/stepzen-samples/apigee-stepzen-sample)
- [x] [with-sveltekit]()

**Comment by carloseberhardt** [comment]
we should talk about with-apigee ... this repo was used to _start_ the work with apigee. it's not updated with latest content, which really lives here: https://github.com/apigee/stepzen

**Comment by Cerchie** [comment]
we now have a good base of samples added
