### ISSUE TITLE
stepzen login cli command gives error

### ISSUE THREAD

**Issue by Vishnu10987** [stepzen-dev/examples#34]
**Describe the bug**
stepzen login command gives an error : 
SyntaxError: Unexpected token {

**To Reproduce**
node version : 8.9.4
npm version : 5.6.0
stepzen version : stepzen@0.16.0

**Expected behavior**
stepzen login should not give a syntax error : SyntaxError: Unexpected token {
we should be able to login successfully.

**Screenshots**

**Desktop (please complete the following information):**
windows OS laptop

![image](https://user-images.githubusercontent.com/34142526/170576752-54fe8641-e509-43d8-a06e-36414b910aff.png)

**Comment by Cerchie** [comment]
HI @Vishnu10987 , does this bug persist after you update your node version to be >=12.0.0?
Here's a resource on how to update: https://www.geeksforgeeks.org/how-to-update-node-js-and-npm-to-next-version/

**Comment by royderks** [comment]
Close as issue is stale, if you're still experiencing this issue please reach out.
