### ISSUE TITLE
Issue with mongodb example

### ISSUE THREAD

**Issue by Ayoseun** [stepzen-dev/examples#35]
**Describe the bug**
I am trying to kickstart a project with stepzen mongodb, everything else seems to work good except when i try to query from stepzen it doesn't work

**Comment by royderks** [comment]
Hello @Ayoseun could you give more details about what isn't working? Please share the error message you're seeing in your terminal or in the response of a GraphQL request.

**Comment by Ayoseun** [comment]
I get the error "Http connector error"
