### ISSUE TITLE
Connection failure. JDBC EXCEPTION

### ISSUE THREAD

**Issue by omen1650ti** [stepzen-dev/examples#81]
stepzen import mysql --db-host='db.introspection.stepzen.net' --db-database='introspection' --db-user='testUserIntrospection' --db-password='HurricaneStartingSample1934' --name='stepzen'
Starting... fail
A problem occurred while processing your import. Please check that the given database details are valid.
DB Error.
Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.: "com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.\n\tat com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)\n\tat com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)\n\tat com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828)\n\tat com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)\n\tat com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)\n\tat com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)\n\tat java.sql/java.sql.DriverManager.getConnection(Unknown Source)\n\tat java.sql/java.sql.DriverManager.getConnection(Unknown Source)\n\tat com.stepzen.introspection.db.DBHandler.getConnection$$anonfun$1$$anonfun$2$$anonfun$1$$anonfun$1(DBHandler.scala:50)\n\tat zio.ZIOCompanionVersionSpecific.attempt$$anonfun$1(ZIOCompanionVersionSpecific.scala:103)\n\tat zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1107)\n\tat zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1007)\n\tat zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:930)\n\tat zio.internal.FiberRuntime.evaluateEffect(FiberRuntime.scala:385)\n\tat zio.internal.FiberRuntime.evaluateMessageWhileSuspended(FiberRuntime.scala:508)\n\tat zio.internal.FiberRuntime.drainQueueOnCurrentThread(FiberRuntime.scala:225)\n\tat zio.internal.FiberRuntime.run(FiberRuntime.scala:138)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)\n\tat java.base/java.lang.Thread.run(Unknown Source)\nCaused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.\n\tat java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)\n\tat java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)\n\tat java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)\n\tat java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)\n\tat com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)\n\tat com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)\n\tat com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)\n\tat com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)\n\tat com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)\n\tat com.mysql.cj.NativeSession.connect(NativeSession.java:120)\n\tat com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:948)\n\tat com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:818)\n\t... 17 more\nCaused by: java.net.UnknownHostException: 'db.introspection.stepzen.net': Name does not resolve\n\tat java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)\n\tat java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(Unknown Source)\n\tat java.base/java.net.InetAddress.getAddressesFromNameService(Unknown Source)\n\tat java.base/java.net.InetAddress$NameServiceAddresses.get(Unknown Source)\n\tat java.base/java.net.InetAddress.getAllByName0(Unknown Source)\n\tat java.base/java.net.InetAddress.getAllByName(Unknown Source)\n\tat java.base/java.net.InetAddress.getAllByName(Unknown Source)\n\tat com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:130)\n\tat com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)\n\t... 20 more\n"

Please help to fix the issue.
@royderks

**Comment by royderks** [comment]
Thanks for submitting an issue. I just tried this with the latest version of the StepZen CLI and couldn't replicate this. Just to check, are you on some sort of VPN? @omen1650ti

**Comment by omen1650ti** [comment]
I was trying following each and every steps according to ypur video but after entering access details of RDS  containing a mysql database suddenly I encountered this error.

**Comment by omen1650ti** [comment]
I tried this way initially,
stepzen import mysql --db-database='w*****rs' --db-host='databaserds.***********.*********1.rds.amazonaws.com' --db-password='******' --db-user='A*****hek' --name=stepzen. I was trying to import my backend this way.
But when I tried:
stepzen import mysql followed by answering the prompts regarding db details i was able to connect successfully. 
Thank you @royderks for responding immediately to the issue.

**Comment by royderks** [comment]
^ It turns out the single quotes lead to issues on Windows. Removing the single quotes work, we'll assess and update the product accordingly

Thanks for raising this issue @omen1650ti
